# Generated by Django 5.1.3 on 2024-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('restaurant', 'Restaurant'), ('delivery', 'Delivery'), ('courier', 'Courier')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delete', 'Delete'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
